# Generated by Django 5.2.5 on 2025-12-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0003_blog_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name="person's full name : "),
        ),
    ]
