# Generated by Django 5.2.5 on 2025-12-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0004_alter_userprofile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('toppings', models.ManyToManyField(to='event_manager.topping')),
            ],
        ),
    ]
