# Generated by Django 5.2.5 on 2025-12-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0006_souse_pizza_souse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'ordering': ['-name'], 'verbose_name_plural': 'toppig'},
        ),
    ]
