# Generated by Django 5.2.5 on 2025-12-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0007_alter_topping_options'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='pizza',
            order_with_respect_to='toppings',
        ),
    ]
