# Generated by Django 5.2.5 on 2025-12-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0008_alter_pizza_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='pizza',
            order_with_respect_to='souse',
        ),
    ]
