# Generated by Django 5.2.5 on 2025-12-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0009_alter_pizza_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'get_latest_by': 'name'},
        ),
    ]
