# Generated by Django 5.2.5 on 2025-12-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0011_alter_pizza_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'default_permissions': ('add', 'change', 'view'), 'get_latest_by': 'name'},
        ),
    ]
