# Generated by Django 5.2.5 on 2025-12-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0013_alter_pizza_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'default_manager_name': 'objects', 'default_permissions': ('change', 'view'), 'get_latest_by': 'name', 'verbose_name': 'Pizza_', 'verbose_name_plural': 'pizzas__'},
        ),
        migrations.AlterModelTable(
            name='pizza',
            table='pizzas',
        ),
    ]
