# Generated by Django 5.2.5 on 2025-12-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0014_alter_pizza_options_alter_pizza_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pizza',
            table='pizzas****',
        ),
    ]
