# Generated by Django 5.2.8 on 2025-12-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0015_alter_pizza_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
