# Generated by Django 5.2.8 on 2025-12-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0016_pizza_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
