# Generated by Django 5.2.8 on 2025-12-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0018_alter_pizza_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='regular_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
