# Generated by Django 5.2.8 on 2025-12-10 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0019_pizza_regular_price_pizza_special_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.blog'),
        ),
    ]
