# Generated by Django 5.2.8 on 2025-12-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0020_pizza_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={},
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe'), ('not going', 'Not Going')], max_length=20),
        ),
        migrations.AlterOrderWithRespectTo(
            name='pizza',
            order_with_respect_to=None,
        ),
        migrations.AlterModelTable(
            name='pizza',
            table=None,
        ),
    ]
