# Generated by Django 5.2.8 on 2025-12-11 05:49

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0021_alter_pizza_options_alter_rsvp_status_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pizza',
            managers=[
                ('piz', django.db.models.manager.Manager()),
            ],
        ),
    ]
