# Generated by Django 5.2.8 on 2025-12-11 06:14

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0022_alter_pizza_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.blog')),
                ('souse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.souse')),
                ('toppings', models.ManyToManyField(to='event_manager.topping')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('piz', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='pizza',
        ),
    ]
