# Generated by Django 5.2.8 on 2025-12-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0023_specialpizza_delete_pizza'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='specialpizza',
            managers=[
            ],
        ),
    ]
